name: "Publish to Docker"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  registry:
    description: "Define registry for this image. Default: 'docker.io'"
    default: 'docker.io'
  tag: 
    description: "How to tag the image. Default: latest"
    default: 'latest'
  build_context: 
    description: "Context of the image to build. Default: ."
    default: '.'

runs:
  using: "composite"
  steps:
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Set the tag
        shell: bash
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Set the username
        shell: bash
        run: |
          if [ -z "${{inputs.registry}}" ]
          then
            echo "registry_username=${{inputs.registry_username}}" >> $GITHUB_ENV
            echo "registry_password=${{inputs.registry_password}}" >> $GITHUB_ENV
            echo "registry_prefix=''" >> $GITHUB_ENV
          else
            echo "registry_username=${{github.repository_owner}}" >> $GITHUB_ENV
            echo "registry_password=${{inputs.registry_password}}" >> $GITHUB_ENV
            echo "registry_prefix=${{inputs.registry}}/" >> $GITHUB_ENV
          fi
      
      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          registry: ${{inputs.registry}}
          username: ${{env.registry_username}}
          password: ${{env.registry_password}}

      - name: Build and Push the Image
        uses: docker/build-push-action@v5
        with:
          context: ${{inputs.build_context}}
          push: true
          tags: ${{env.registry_prefix}}${{env.registry_username}}/${{inputs.image_name}}:${{env.final_tag}}
